### ISSUE TITLE
Error converting result to JSON when lowest_price of release is null

### ISSUE THREAD

**Issue by arenner-git** [damidhagor/DiscogsApiClient#1]
Hi there,

first, thanks for your great client!
One thing, I've just encountered when playing around with it. If you try to retrieve a release, where the "lowest_price" property is null, the following exception is thrown:

```
System.Text.Json.JsonException: The JSON value could not be converted to DiscogsApiClient.Contract.Release.Release. Path: $.lowest_price | LineNumber: 0 | BytePositionInLine: 2883.
System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
```

You can try it f.e. with the following release id: 11993112

Maybe you can fix that in your next release!

Greetings

**Comment by damidhagor** [comment]
Hi. First thank you for using and enjoying the library!
Sorry for not answering faster. For some reason GitHub does not send E-Mail notifications when something happens with the repository.

I took note of the issue and will fix the issue with this property in the next release.

Unfortunately the Discogs Api surface isn't well documented so every bug being called out is helpful to straighten the client out!

**Comment by damidhagor** [comment]
I've fixed the issue. The new version 3.0.1 should work now for your issue. :)

**Comment by arenner-git** [comment]
> I've fixed the issue. The new version 3.0.1 should work now for your issue. :)

works like a charm! thx for the fix!
